### ISSUE TITLE
When using as external lib, is it possible to use target_link_libraries?

### ISSUE THREAD

**Issue by ldXiao** [patrikhuber/eos#235] opened 2018-12-01 02:16 UTC
Dear all, as the creator has mentioned in the main page, we can directly include the directory in the project.

But can we use the syntax like 
Find_Package(eos.....)
....
target_link_directories(...)
?

**Comment by patrikhuber** [comment] 2018-12-12 11:03
Hi!

Unfortunately this is not yet possible. This would be part of #68.
But it shouldn't be a big issue - since eos is a header-only library, you could just add eos's include directory to your project using `target_include_directories`. No linking or compilation is required.

**Comment by patrikhuber** [comment] 2018-12-12 11:04
I am closing this as a duplicate of #68 :-)

**Closed by patrikhuber** 2018-12-12 11:04 UTC
