### ISSUE TITLE
Head pose estimation performance

### ISSUE THREAD

**Issue by mwlodarczyk** [patrikhuber/eos#154] opened 2017-09-26 22:19 UTC
Hi,

I am trying to validate eos head pose estimation performance. For this purpose, I am using Pointing'04 dataset (http://www-prima.inrialpes.fr/Pointing04/data-face.html). 

However, the obtained errors are not satisfactory. I am using the following procedure:
1. The sfm_shape_3448 model is evaluated
2. Dlib library is used to get face landmarks
3. The fit-model example app is used. The code changes are only related to file path and landmarks reading

Please find the sample results:
1. Real yaw angle: 0 degrees. Estimated: -10 degrees
2. Real pitch angle: 30 degrees. Estimated: 17 degrees

I am attaching the debug images. Any tips / hints?

![image](https://user-images.githubusercontent.com/1088046/30886918-6ffd00c4-a319-11e7-9db8-3f129aa38503.png)

**Comment by patrikhuber** [comment] 2017-09-26 22:40
Hi Michał!

It seems to me like the ground truth from the Pointing database is just not good. The guy in this image definitely is not looking straight into the camera, he's got some yaw angle, and I'd say -10° (looking to the left (from the subject's perspective)) is a pretty good estimate. 
About the pitch angle, I'm not surprised that it's a bit off, pitch is really hard to precisely estimate. But from my personal experience, I really don't think that camera is at 30° pitch angle.

It's not the only database with that issue, the more attentive researchers out there have noticed and noted before that for example for MultiPIE, some of the ground truth angles are also not really computed correctly.

One other thing to watch out for is that Euler angles are an ambiguous representation for pose (see e.g. [here](https://en.wikipedia.org/wiki/Euler_angles)). An order needs to be specified as well. So it's much better to use something like quaternions to represent (and compare) rotations (eos gives you a rotation quaternion by default). The problem is that many of these databases just give you Euler angles and don't even specify with which system and rotation order they're specified...

**Comment by Larumbergera** [comment] 2017-09-27 12:12
Hi, 

Regarding the databases, I'm researching on HPE and and we have created two public databases for head tracking and pose estimation. The detailed information about the first one is [here](http://www.sciencedirect.com/science/article/pii/S1077314215000934). The second one is a synthetic replica of the first one and has been published today (paper has been accepted to ACVR/ICCV but is not yet published).

You can download databases from [here](http://gi4e.unavarra.es/databases/).

One other hand, in the article describing the synthetic database, we propose a method in which, using this software for tracking ([superviseddescent](https://github.com/patrikhuber/superviseddescent)), and POSIT, we are able to improve the HPE.  

Cheers,

Andoni.

**Comment by mwlodarczyk** [comment] 2017-09-27 14:19
Hi All,

Thanks for the great answers. Generally, my research is oriented to face recognition. I am using the COMPACT dataset (http://biometrics.dmcs.pl/projects/compact). In this particular set,  a single registration sample is represented by 57 images. Thus, I want to use HPE to select only the list of 3 / 5 similar faces instead of doing useless comparisons.

Theoretically, the HPE error would propagate in the same way to both registration and probe images and should not affect my method. However, for the paper, I would like to select the best possible approach and that is why I want to check the performance. For instance, I am referring to the paper entitled: "Yaw Estimation Using Cylindrical and Ellipsoidal Face Models" http://ieeexplore.ieee.org/document/6807708/), where the reference results are much better.

I will think about using the dataset collected by @Larumbergera. Also, the synthetic data sounds great - they may be a good reference for my studies.

Once again, thanks for great answers. If you have any further suggestions, they are all welcome :)

**Comment by patrikhuber** [comment] 2017-09-27 17:59
Great!

As already mentioned, I'm always very suspicious of papers that do experiments on HPE but don't even mention what Euler angle convention they or their datasets used. In my opinion, that results in meaningless results.

If you've got good landmarks, and good ground truth (and compare it in a meaningful way), I would be pretty confident that the HPE that eos estimates is pretty good. I would agree you'd probably see a noticeable error in the pitch estimation (a few, maybe up to 10°), that's quite hard to precisely estimate.

Also, for your task of selecting images for face recognition, you probably don't care if the HPE error is 2° or 5°, both will do?

I will close this, as it's not an issue with the eos library. But please feel free to continue the discussion or check back with any questions or results you may have, I'd be interested to hear about eos's performance.

**Closed by patrikhuber** 2017-09-27 17:59 UTC

**Comment by mwlodarczyk** [comment] 2017-10-09 12:05
Hi All,

I am coming back with my latest results. I am using the GI4E dataset, as suggested by @Larumbergera. Here is a sample histogram for pitch angle. The results are presented for 'user_01' videos:

![eos_gi4e](https://user-images.githubusercontent.com/1088046/31337127-31874ee0-acfa-11e7-8a75-2612d25a0c57.png)

The average error is around -8 degrees. However, it can be noticed that the results are shifted. This probably means that the ground truth is not properly correlated with EOS. However, when analyzing all users, it can be noticed that this 'shift' is not constants: For instance:

User_1 shift: ~ -8
User_2 shift: ~ -9
User_3 shift~ -1
User_5 shift:~ -2
User_6 shift:~ -2.5

I am thinking about analyzing differences between frames - for instance, when the change between ground truth is 1 degree, the same should be reported by EOS.

@patrikhuber, @Larumbergera: Any suggestions?

Best,
Michal

**Comment by Larumbergera** [comment] 2017-10-09 12:46
Hi,

Can you organize the results according to the guided videos (videos 01 to 06) instead of users?
Be careful with video 04 (especially for the user 04) because the tracking fails.

Yes, I think analyze differences between frames is a better approach (or just analyze differences between each frame and the first one). 

Regards,

Andoni.

**Comment by patrikhuber** [comment] 2017-10-09 16:41
Hi Michał,

Very interesting! Do you think you could share the curves for yaw and roll as well? Would be very interesting to see.

Where does the ground truth head-pose in the GI4E database come from? From a sensor? 
Do you compare the angles within the same [Euler-angle convention](https://en.wikipedia.org/wiki/Euler_angles)?

Cheers,
Patrik

**Comment by mwlodarczyk** [comment] 2017-10-09 19:08
Hi All,

This is the histogram for yaw angle, obtained by analyzing the differences between frames. It is a development version, so the final results will be a bit different.

<img width="703" alt="eos_2" src="https://user-images.githubusercontent.com/1088046/31354216-d8aaaa2e-ad35-11e7-852a-84eaac416c28.png">

I want to generate same curves for both yaw, roll and pitch angle. I am working on a paper, where I want to compare the performance of HPE from EOS with geometric model proposed by Narayanan et al. in " 
Estimation of Driver Head Yaw Angle Using a Generic Geometric Model". Their method is for yaw angle only, for roll the geometric model can be easily based on landmarks. For pitch, I was not able to find any geometric based solution. Currently, I am trying to calculate the histogram by analyzing the differences instead of absolute values. Apart from that, I want to show how to use HPE in a biometric system that I have built to filter the registration data. This allows me to skip some comparisons and reduce the computing time.

As for the ground truth for GI4E database: the reference values are collected by a sensor mounted on subject's head. The euler-angle convention seems to be different: to get proper yaw and roll angles, I need to change the sign for both yaw and roll angles. However, for pitch the sign is correct.  

Is it possible to change the Euler convention used by EOS? Maybe the absolute values are not correct because of that? The GI4E dataset provides the following reference values: Tx, Ty, Tz, Roll, Yaw, Pitch. These values corresponds to the 3 translations and 3 rotations. Maybe it will be better to base the comparison on Tx, Ty, Tz? But I am not sure how to achieve that?

Best,
Michal

**Comment by mwlodarczyk** [comment] 2017-10-09 20:10
Hi All,

Please find some more results, when analyzed two videos for user_01. I was analyzing differences between frames.

![pitch](https://user-images.githubusercontent.com/1088046/31356541-acb483be-ad3e-11e7-8ed7-598385f31351.png)

![roll](https://user-images.githubusercontent.com/1088046/31356544-b01f5cea-ad3e-11e7-9729-b4ce929d037a.png)

![yaw](https://user-images.githubusercontent.com/1088046/31356547-b47a04d4-ad3e-11e7-9730-cc1e6701de49.png)

**Comment by Larumbergera** [comment] 2017-10-10 07:04
Hi, 

@patrikhuber: Angle convention used are z-y'-x'', employing the [camera coordinate system](https://ars.els-cdn.com/content/image/1-s2.0-S1077314215000934-gr1.jpg).

> Where does the ground truth head-pose in the GI4E database come from? From a sensor? 

GI4E have two Head Pose datasets, a real one and a synthetic one.

In the real one a commercial magnetic sensor-transmitter system has been employed in order to obtain the head pose ground-truth. Detailed information about real one can be found [here](http://www.sciencedirect.com/science/article/pii/S1077314215000934). 

In the synthetic one, we take the head pose ground-truth from the real one, create the [rotation matrix](https://wikimedia.org/api/rest_v1/media/math/render/svg/45583b01e584306f30f616307c8e53c349705b12) and transform a head model (Basel Face Model) in each frame with the corresponding rotation and translation values.

@mwlodarczyk :

> When checking differences between frames, it works great!

Differential error is the one that best describes the performance of a head pose estimator.

> Maybe it will be better to base the comparison on Tx, Ty, Tz?

You can also compare Tx, Ty and Tz, but in literature only rotations are usually compared.

Regards,

Andoni.
