### ISSUE TITLE
The 3D face reconstruction image looks so weird， how to improve it? 

### ISSUE THREAD

**Issue by Chen-Jinlong** [patrikhuber/eos#289] opened 2019-12-09 10:25 UTC
Hi, Patrik.
I got a problem when applied BFM2017 on eos. Since bfm2017 had no blendshapes file, I used expression PCA model which was extracted from the BFM2017 converted file. And it worked successfully, but the result was not so satisfied. The reconstructed image is below:
![ ]https://www.picb.cc/image/keyDWi
![ ]https://www.picb.cc/image/keyERL
The shape was almost correct, but the color or the texture was not. It's obvious that there was a ghost around the eyes. I tried other images, and the results still appeared.
How can I fix this problem? Do you have some advice?

**Comment by patrikhuber** [comment] 2019-12-09 11:00
Duplicate of #288

**Closed by patrikhuber** 2019-12-09 11:00 UTC
