### ISSUE TITLE
When I display the out.obj with RendererParameters, the model's position is different with the fit_shape_and_pose?

### ISSUE THREAD

**Issue by yygbruce** [patrikhuber/eos#292] opened 2020-01-08 06:21 UTC
I mean that I can display the out.obj correctly with RendererParamters, but the position is different with the fit_shape_and_pose.I can use RendererParameters draw wireframe as you, so I get the correct parameters from eos.I want to select the triangle and the Intersection point when I pick the screen(the model's position is same with the fit_shape_and_pose).I have readed the source code, and know the fountion of ray_triangle_intersect, but I cannot find the correct ray_origin and ray_direction when I pick the screen.Can you give me some advice?

**Comment by patrikhuber** [comment] 2020-01-08 20:46
Please don't open duplicate issues. Closing this as a duplicate of #291.

**Closed by patrikhuber** 2020-01-08 20:46 UTC
